<a href="https://colab.research.google.com/github/dohyeon-kim012/SQL_1/blob/main/Numpy_learning(%EC%98%A4%ED%9B%84).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np11 = np.array([2, 4, 6, 8], dtype=np.int16)
np12  = np.array([3, 6, 9, 12, 15], dtype=np.int16)

In [ ]:
np11.shape, np12.shape

((4,), (5,))

In [ ]:
np11 += 5
np11

array([ 7,  9, 11, 13], dtype=int16)

In [ ]:
np11 > 10, np11 == 11   

(array([False, False,  True,  True]), array([False, False,  True, False]))

In [ ]:
np13 = np.arange(1, 11)
np13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np13[3:7] +=5
np13

array([ 1,  2,  3,  9, 10, 11, 12,  8,  9, 10])

In [ ]:
np13[4] = 90

In [ ]:
np13[6:] = 0
np13

array([ 1,  2,  3,  9, 90, 11,  0,  0,  0,  0])

In [ ]:
a1 = [1, 2, 3, 4, 5]
a2 = [6, 7, 8, 9, 10]
a3 = [11, 12, 13, 14, 15]
np2 = np.array([a1, a2, a3])
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np3 = np2[:2,:2] + 5    # [행, 열] -> 1열,1행까지의 범위 값에 +5
np3

array([[ 6,  7],
       [11, 12]])

In [ ]:
np4 = np2[:,2:4] * 10   # 모든 행, 2-3열까지 범위 값에 * 10
np4

array([[ 30,  40],
       [ 80,  90],
       [130, 140]])

In [ ]:
np5 = np.arange(1, 16)
np5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np5.reshape(3, 5)  #arange와 reshape을 이용해서 1차원을 2차원으로 만들기

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np6 = np.arange(10, 241, 10)
np6, np6.ndim, np6.shape  # ndim : array의 차원 확인

(array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]), 1, (24,))

In [ ]:
np7 = np6.reshape(2, 3, 4)    # np6을 3행 4열 2개로 나누어 3차원으로 만듦
np7.ndim, np7.shape, np7

(3, (2, 3, 4), array([[[ 10,  20,  30,  40],
         [ 50,  60,  70,  80],
         [ 90, 100, 110, 120]],
 
        [[130, 140, 150, 160],
         [170, 180, 190, 200],
         [210, 220, 230, 240]]]))

In [ ]:
np7[0, 2, 2]

110

In [ ]:
np7[0,1,1:3]

array([60, 70])

In [48]:
np8 = np6.reshape(2, 3, 2, 2)
np8.ndim, np8

(4, array([[[[ 10,  20],
          [ 30,  40]],
 
         [[ 50,  60],
          [ 70,  80]],
 
         [[ 90, 100],
          [110, 120]]],
 
 
        [[[130, 140],
          [150, 160]],
 
         [[170, 180],
          [190, 200]],
 
         [[210, 220],
          [230, 240]]]]))

5/18 오후과제

In [49]:
np7

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [50]:
np7[0,0,2]

30

In [51]:
np7[0,2]

array([ 90, 100, 110, 120])

In [53]:
np7[1,1:3,:2]

array([[170, 180],
       [210, 220]])

In [56]:
np7[0,1:, 2:],np7[1,:2,2:]

(array([[ 70,  80],
        [110, 120]]), array([[150, 160],
        [190, 200]]))

In [61]:
np7[1, 1:, 2:] = np7[1, 1:, 2:] - 40
np7[0:2, 1:3, 2:]

array([[[ 70,  80],
        [110, 120]],

       [[150, 160],
        [190, 200]]])