<a href="https://colab.research.google.com/github/dohyeon-kim012/SQL_1/blob/main/Numpy_learning(%EC%98%A4%EC%A0%84).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
t = [ i * 3 for i in range(1, 11)]

In [5]:
a = [1, 2, 3]
b = [4, 5, 6]
c = [a, b]

In [4]:
np1 = np.array(t) # 1차원

In [6]:
type(np1)

numpy.ndarray

In [7]:
np1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [8]:
np1 + 1

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [11]:
np1.dtype
# 파란색은 변수, 보라색은 함수

dtype('int64')

In [12]:
np1.shape # 1차원

(10,)

In [14]:
np1.mean()
# np1 배열의 평균값 구함

16.5

In [15]:
np1.nbytes
# 원소 1개당 8byte 이므로 총 10개면 80byte

80

In [16]:
np1.itemsize

8

In [17]:
np2 = np.array(c) # 2차원

In [18]:
np2.shape # 2차원
# np2 array의 행과 열의 개수를 확인 (행=2, 열=3)

(2, 3)

In [19]:
np2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np2.nbytes

48

In [21]:
np2 + 10  # broadcasting 연산(여러 개를 가지고 연산)

array([[11, 12, 13],
       [14, 15, 16]])

In [22]:
np2.T
# 테이블의 행과 열을 맞바꿈

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
np2.sum()

21

In [23]:
np2.sum(axis=0)  # 열(I)끼리 더함

array([5, 7, 9])

In [24]:
np2.sum(axis=1)  # 행(J)끼리 더함 

array([ 6, 15])

In [30]:
tt1 = [i for i in range(2, 21, 2)]
tt2 = [i*3 for i in range(1, 11)]
tt3 = [i for i in range(5, 51, 5)]

In [31]:
tt1, tt2, tt3

([2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [32]:
ttt = [tt1, tt2, tt3]
np22 = np.array(ttt)

In [44]:
np22

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [43]:
type(ttt), type(np22)

(list, numpy.ndarray)

In [42]:
np22.sum(), np22[0].sum(), np22[1].sum(), np22[2].sum()

(550, 110, 165, 275)

In [39]:
np22.sum(axis=1)

array([110, 165, 275])

In [45]:
np22.mean(axis=1), np22.mean(axis=0)

(array([11. , 16.5, 27.5]),
 array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
        20.        , 23.33333333, 26.66666667, 30.        , 33.33333333]))

In [46]:
np23 = np22.T
np23

array([[ 2,  3,  5],
       [ 4,  6, 10],
       [ 6,  9, 15],
       [ 8, 12, 20],
       [10, 15, 25],
       [12, 18, 30],
       [14, 21, 35],
       [16, 24, 40],
       [18, 27, 45],
       [20, 30, 50]])

In [47]:
np23.min(), np23.max()

(2, 50)

In [48]:
np23.min(axis=1), np23.max(axis=0)

(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]), array([20, 30, 50]))

In [50]:
np23.shape, np23.reshape(2, 15)

((10, 3), array([[ 2,  3,  5,  4,  6, 10,  6,  9, 15,  8, 12, 20, 10, 15, 25],
        [12, 18, 30, 14, 21, 35, 16, 24, 40, 18, 27, 45, 20, 30, 50]]))

In [51]:
np23.reshape(2, 20)

ValueError: ignored

In [53]:
np24 = np.array([i for i in range(1, 25)])

In [56]:
np24.reshape(3, 8), np24.reshape(4, 6)

(array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]), array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]))

In [61]:
np11 = np.array([2, 4, 6, 8, 10])
np11.dtype  # 64bit

dtype('int64')

In [62]:
np12 = np.array([2, 4, 6, 8, 10], dtype = np.int16)
np12.dtype  # 16bit

dtype('int16')

In [94]:
np11.itemsize, np12.itemsize, np11.nbytes , np12.nbytes
# 64bit=8byte, 16bit=2byte -> itemsize(원소 하나당 사이즈)
# 각각 원소가 5개씩이므로 nbytes는 각각 40, 10byte

(8, 2, 40, 10)

In [65]:
np200 = np.array([2.3, 4.5, 6.7])
np200.dtype, np200.nbytes

(dtype('float64'), 24)

In [66]:
np201 = np.array([2.3, 4.5, 6.7], dtype = np.float16)
np201.nbytes  # 16bit=2byte, 원소가 3개라 총 6byte

6

In [67]:
np13 = np.array([2, 4, 5], dtype='uint')  # u -> unsigned, uint -> 양수로만 값을 매김

In [68]:
np.empty([2, 5])

array([[ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667],
       [20.        , 23.33333333, 26.66666667, 30.        , 33.33333333]])

In [69]:
np.empty([7, 2])

array([[4.64863235e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 2.61354267e-306]])

In [70]:
np.zeros([3, 4]), np.ones([3, 4])

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [72]:
np.arange(6), np.arange(1, 20, 2)

(array([0, 1, 2, 3, 4, 5]), array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]))

In [77]:
gdan2 = [i*2 for i in range(1, 10)]
gdan2

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [79]:
gdan3 = [i*3 for i in range(1, 10)]
gdan4 = [i*4 for i in range(1, 10)]
gdan5 = [i*5 for i in range(1, 10)]
gdan6 = [i*6 for i in range(1, 10)]
gdan7 = [i*7 for i in range(1, 10)]
gdan8 = [i*8 for i in range(1, 10)]
gdan9 = [i*9 for i in range(1, 10)]
gdan0 = [gdan2,gdan3, gdan4, gdan5, gdan6,gdan7,gdan8,gdan9]

In [81]:
gdan=np.array([gdan0], dtype=np.int16)

In [82]:
gdan

array([[[ 2,  4,  6,  8, 10, 12, 14, 16, 18],
        [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
        [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
        [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
        [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
        [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
        [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
        [ 9, 18, 27, 36, 45, 54, 63, 72, 81]]], dtype=int16)

In [85]:
gdan[:,1] + 50  # 1행을 추출해서 +50 계산  (열 추출: [1,:])

array([[53, 56, 59, 62, 65, 68, 71, 74, 77]], dtype=int16)

In [88]:
gdan[:,3] * 100

array([[ 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]],
      dtype=int16)

In [95]:
gdan.reshape(3,24)

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18,  3,  6,  9, 12, 15, 18, 21,
        24, 27,  4,  8, 12, 16, 20, 24],
       [28, 32, 36,  5, 10, 15, 20, 25, 30, 35, 40, 45,  6, 12, 18, 24,
        30, 36, 42, 48, 54,  7, 14, 21],
       [28, 35, 42, 49, 56, 63,  8, 16, 24, 32, 40, 48, 56, 64, 72,  9,
        18, 27, 36, 45, 54, 63, 72, 81]], dtype=int16)

In [96]:
import numpy as np
gdan = [[x, y, x*y] for x in range(2,10) for y in range(1,10)]
ngdan = np.array(gdan, dtype = np.int16)
ngdan

array([[ 2,  1,  2],
       [ 2,  2,  4],
       [ 2,  3,  6],
       [ 2,  4,  8],
       [ 2,  5, 10],
       [ 2,  6, 12],
       [ 2,  7, 14],
       [ 2,  8, 16],
       [ 2,  9, 18],
       [ 3,  1,  3],
       [ 3,  2,  6],
       [ 3,  3,  9],
       [ 3,  4, 12],
       [ 3,  5, 15],
       [ 3,  6, 18],
       [ 3,  7, 21],
       [ 3,  8, 24],
       [ 3,  9, 27],
       [ 4,  1,  4],
       [ 4,  2,  8],
       [ 4,  3, 12],
       [ 4,  4, 16],
       [ 4,  5, 20],
       [ 4,  6, 24],
       [ 4,  7, 28],
       [ 4,  8, 32],
       [ 4,  9, 36],
       [ 5,  1,  5],
       [ 5,  2, 10],
       [ 5,  3, 15],
       [ 5,  4, 20],
       [ 5,  5, 25],
       [ 5,  6, 30],
       [ 5,  7, 35],
       [ 5,  8, 40],
       [ 5,  9, 45],
       [ 6,  1,  6],
       [ 6,  2, 12],
       [ 6,  3, 18],
       [ 6,  4, 24],
       [ 6,  5, 30],
       [ 6,  6, 36],
       [ 6,  7, 42],
       [ 6,  8, 48],
       [ 6,  9, 54],
       [ 7,  1,  7],
       [ 7,  2, 14],
       [ 7,  

In [97]:
ngdan[9:18,]

array([[ 3,  1,  3],
       [ 3,  2,  6],
       [ 3,  3,  9],
       [ 3,  4, 12],
       [ 3,  5, 15],
       [ 3,  6, 18],
       [ 3,  7, 21],
       [ 3,  8, 24],
       [ 3,  9, 27]], dtype=int16)

In [100]:
ngdan[9:18, 2] = ngdan[9:18, 2] + 50
ngdan[9:18,]

array([[ 3,  1, 53],
       [ 3,  2, 56],
       [ 3,  3, 59],
       [ 3,  4, 62],
       [ 3,  5, 65],
       [ 3,  6, 68],
       [ 3,  7, 71],
       [ 3,  8, 74],
       [ 3,  9, 77]], dtype=int16)

In [101]:
ngdan[27:36, 2] = ngdan[27:36, 2] * 100
ngdan[27:36,]

array([[   5,    1,  500],
       [   5,    2, 1000],
       [   5,    3, 1500],
       [   5,    4, 2000],
       [   5,    5, 2500],
       [   5,    6, 3000],
       [   5,    7, 3500],
       [   5,    8, 4000],
       [   5,    9, 4500]], dtype=int16)